#!/usr/bin/env bash

git clean -Xf ./dev

concurrently \
  --names "cat-walkers,bad-birders,dope-dogs" \
  "./scripts/pg-prepare ./dev/apps/cat-walkers" \
  "./scripts/pg-prepare ./dev/apps/bad-birders" \
  "./scripts/pg-prepare ./dev/apps/dope-dogs"
