#!/usr/bin/env bash

nodemon -w . --exec concurrently \
  --kill-others \
  --names "cat-walkers,bad-birders,dope-dogs" \
  "./scripts/start ./dev/apps/cat-walkers" \
  "./scripts/start ./dev/apps/bad-birders" \
  "./scripts/start ./dev/apps/dope-dogs"
