#!/usr/bin/env node


const getApp = require('../lib/getApp')


const app = getApp(process.argv[2] || '.')
if (!app){
  console.error(`app not found`)
  process.exit(1)
}

async function main(){

  const schema = await readFile(SCHEMA_PATH)
  await app.pg.query(`${schema}`)
}
main().then(
  () => { process.exit(0) },
  error => { console.error(error); process.exit(1) },
)

// const app = createApp(config)
// app.start(error => {
//   if (error) console.error(error)
//   else console.log(`${app.name} PORT=${app.port} ${app.url}`)
// })
