#!/usr/bin/env node

const getApp = require('../lib/getApp')

const app = getApp(process.argv[2] || '.')
if (!app){
  console.error(`app not found`)
  process.exit(1)
}
console.log(app)

// const app = createApp(config)
// app.start(error => {
//   if (error) console.error(error)
//   else console.log(`${app.name} PORT=${app.port} ${app.url}`)
// })
