#!/usr/bin/env node

if (process.argv[2]) process.chdir(process.argv[2])

const app = require('../app')

async function main(){
  await app.pg.resetSchema()
}
main().then(
  () => { process.exit(0) },
  error => { console.error(error); process.exit(1) },
)
