#!/usr/bin/env node

const Path = require('path')
const http = require('http')
const { createApp } = require('../app')

const configPath = Path.resolve(process.argv[2] || '../config.json')
if (!configPath) {
  console.error(`configPath=${configPath}`)
  process.exit(1)
}

const config = require(configPath)
if (process.env.PORT) config.port = process.env.PORT
const app = createApp(config)
app.start(error => {
  if (error) console.error(error)
  else console.log(`${app.name} PORT=${app.port} ${app.url}`)
})
