#!/usr/bin/env node

const { createApp } = require('../app')

const Apps = [
  require('../dev/apps/CatWalkers'),
  require('../dev/apps/BadBirders'),
  require('../dev/apps/DopeDogs'),
]

const apps = []
for (const options of Apps) {
  const app = createApp(options)
  apps.push(app)
  app.start(error => {
    if (error) console.error(error)
    else console.log(`${app.name} ${app.url}`)
  })
}
