#!/usr/bin/env bash

concurrently \
  --names "cat-walkers,bad-birders,dope-dogs" \
  "./scripts/start ./dev/apps/cat-walkers" \
  "./scripts/start ./dev/apps/bad-birders" \
  "./scripts/start ./dev/apps/dope-dogs"
