#!/usr/bin/env node

const Path = require('path')
const getApp = require('../lib/getApp')

const app = getApp(process.argv[2] || '.')
if (!app){
  console.error(`app not found`)
  process.exit(1)
}

app.start().then(
  () => {
    console.log(`${app.name} PORT=${app.port} ${app.url}`)
  },
  error => {
    console.error(error)
  },
})
